### ISSUE TITLE
Compile-time elision doesn't work (as expected)

### ISSUE THREAD

**Issue by jeaye** [ptaoussanis/tufte#10] opened 2016-09-01 06:04 UTC
When I set `export TUFTE_MIN_LEVEL=6` as part of my build, I get the appropriate output from tufte, as the code dictates: https://github.com/ptaoussanis/tufte/blob/master/src/taoensso/tufte.cljx#L122

Only when I set the run-time value, however, with `(tufte/set-min-level! 6)`, can I actually disable tufte. This issue is pressing because Google App Engine prohibits the creation of threads all willy-nilly and tufte is still creating threads with the supposed compile-time elision.

Can you shed some light on why this might be the case, that having tufte acknowledge my compile-time min level is insufficient to actually stop it from working? Furthermore why the run-time value works instead?

Thanks for your time and for the awesome Clojure projects. timbre, tufte, and nippy have all been very helpful in my work.

**Comment by ptaoussanis** [comment] 2016-09-01 06:10
Hi there!

Sorry, could you possibly provide a short reproducible example with an example of the output you're getting vs expecting? Just have my hands very full atm and struggling to parse your description of the problem here. Thanks!

> Thanks for your time and for the awesome Clojure projects. timbre, tufte, and nippy have all been very helpful in my work.

You're very welcome, thanks for saying so!

**Comment by ptaoussanis** [comment] 2016-09-01 06:24
Quick update to mention that the compile-time levels do appear to be working correctly on my end?:

```clojure
(do
  (def compile-time-min-level 2)
  (profiled {} (p :foo "foo"))) => profiling enabled

(do
  (def compile-time-min-level 6)
  (profiled {} (p :foo "foo"))) => profiling disabled
```

> Google App Engine prohibits the creation of threads all willy-nilly and tufte is still creating threads with the supposed compile-time elision.

Will also note that Tufte should not create threads even when profiling is enabled, so not sure what problem you're running into exactly but it might not be thread creation? An example would help with debugging + to make sure we're talking about the same things.

Thanks,

**Comment by jeaye** [comment] 2016-09-01 06:46
The thread creation is done by `delay`, which tufte uses in at least three places. I'm setting `TUFTE_MIN_LEVEL` when I build my uberwar. I can see that tufte writes to stdout with:

```text
Building uberwar
Compiling toy-server.core
Compile-time (elision) Tufte min-level: 6
Compiling toy-server.datastore
Compiling toy-server.debug
Compiling toy-server.game
Compiling toy-server.request
Compiling toy-server.session
Compile-time (elision) Tufte min-level: 6
Created /Users/jeaye/projects/toy-server/target/uberjar/toy-server-0.1.0-SNAPSHOT-standalone.war
```

Yet, when I run it, tufte doesn't elide. If I set the run-time level, these issues go away. Here's a stack trace showing what's happening (I call `prof` and tufte derefs a delay).

```text
 java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "modifyThreadGroup")

        at java.security.AccessControlContext.checkPermission (AccessControlContext.java:484)
        at java.security.AccessController.checkPermission (AccessController.java:698)
        at java.lang.SecurityManager.checkPermission (SecurityManager.java:549)
        at com.google.apphosting.runtime.security.CustomSecurityManager.checkPermission (CustomSecurityManager.java:55)
        at com.google.apphosting.runtime.security.CustomSecurityManager.checkAccess (CustomSecurityManager.java:136)
        at java.lang.ThreadGroup.checkAccess (ThreadGroup.java:315)
        at java.lang.Thread.init (Thread.java:391)
        at java.lang.Thread.init (Thread.java:349)
        at java.lang.Thread.<init> (Thread.java:461)
        at taoensso.tufte.impl$fn__2583$fn__2584.invoke (impl.clj:189)
        at clojure.lang.Delay.deref (Delay.java:37)
        at clojure.core$deref.invokeStatic (core.clj:2228)
        at clojure.core$deref.invoke (core.clj:2214)
        at taoensso.tufte.impl$handle_BANG_.invokeStatic (impl.clj:186)
        at taoensso.tufte.impl$handle_BANG_.invoke (impl.clj:186)
        at toy_server.core$prof$fn__300.invoke (core.clj:156)
        at compojure.response$fn__4141.invokeStatic (response.clj:33)
        at compojure.response$fn__4141.invoke (response.clj:21)
        at compojure.response$fn__4114$G__4109__4121.invoke (response.clj:6)
        at compojure.core$make_route$fn__5487.invoke (core.clj:135)
        at compojure.core$wrap_route_middleware$fn__5480.invoke (core.clj:122)
        at compojure.core$wrap_route_info$fn__5484.invoke (core.clj:126)
        at compojure.core$if_route$fn__5442.invoke (core.clj:45)
        at compojure.core$if_method$fn__5432.invoke (core.clj:27)
        at compojure.core$routing$fn__5494.invoke (core.clj:151)
        at clojure.core$some.invokeStatic (core.clj:2592)
        at clojure.core$some.invoke (core.clj:2583)
        at compojure.core$routing.invokeStatic (core.clj:151)
        at compojure.core$routing.doInvoke (core.clj:148)
        at clojure.lang.RestFn.applyTo (RestFn.java:139)
        at clojure.core$apply.invokeStatic (core.clj:648)
        at clojure.core$apply.invoke (core.clj:641)
        at compojure.core$routes$fn__5498.invoke (core.clj:156)
        at ring.middleware.params$wrap_params$fn__5817.invoke (params.clj:64)
        at liberator.dev$wrap_trace$fn__5760.invoke (dev.clj:234)
        at liberator.dev$wrap_trace_header$fn__5751.invoke (dev.clj:211)
        at clojure.lang.Var.invoke (Var.java:379)
        at toy_server.listener$_contextInitialized$fn__11.invoke (listener.clj:1)
        at ring.util.servlet$make_service_method$fn__380.invoke (servlet.clj:129)
        at toy_server.servlet$_service.invokeStatic (servlet.clj:1)
        at toy_server.servlet$_service.invoke (servlet.clj:1)
        at toy_server.servlet.service (Unknown Source)
```

**Comment by jeaye** [comment] 2016-09-01 06:52
Following the trail, we see this bit from `impl.cljx`:

```clojure
(defonce ^:private handler-thread_
  (delay
    (let [f (fn []
              (loop []
                (let [m (.take handler-queue)]
                  ;; Note: just drop if no registered handlers
                  (handle-blocking! m)
                  (recur))))]
      (doto (Thread. f)
        (.setDaemon true)
        (.start)))))
```

Either way, the fact that tufte is spawning threads isn't the issue; the issue is that exporting an environment variable to set the compile-time level acts as though it's valid, but doesn't elide for me.

Will you please let me know if you can set `TUFTE_MIN_LEVEL` through bash, to 6, and have tufte properly elide for you?

**Comment by ptaoussanis** [comment] 2016-09-01 07:02
> The thread creation is done by delay, which tufte uses in at least three places.

Delays do not create threads, they're just a function call. Only place Tufte will create a (single) thread is for the `profile` handling worker.

Will check to confirm that elision properly prevents the realisation of the handling worker, thanks for the extra debug info.

**Comment by jeaye** [comment] 2016-09-01 07:15
> Delays do not create threads, they're just a function call. Only place Tufte will create a (single) thread is for the profile handling worker.

Yep, you're right; I realized my mistake when I looked more closely at the back trace.

> Will check to confirm that elision properly prevents the realisation of the handling worker, thanks for the extra debug info.

Thanks; it's late for me, but, if you aren't able to pinpoint or reproduce, I may be able to get a test project up about 20 hours from now.

**Comment by ptaoussanis** [comment] 2016-09-01 07:15
Yeah sorry- struggling to reproduce on my end - elision is working as expected, and properly preventing any `profile` handle calls (which'd be necessary to trigger the creation of a handling worker thread).

Unfortunately won't have any more time to look into this today, but here's some further debugging ideas:

You can try rule out any environment-var issues by trying a fork with a hard `(def compile-time-min-level 6)`. You can also add a throw/println on the `handler-thread_` realisation. If the elision then works as expected, the issue is with your environment/aot.

If you're still seeing an error then you can check if your throw/println is executing. If so, then let me know (would imply something is buggy) - otherwise, looks like something other than the thread creation is tripping up GAE.

Will try check in on this again tomorrow, cheers!

**Comment by ptaoussanis** [comment] 2016-09-06 13:58
Hi @jeaye, any update on this?

**Comment by jeaye** [comment] 2016-09-06 17:42
This caught me just before a vacation where I'm not spending much time around a computer; I wasn't able to get it working, so I do think there's an issue, but I won't be able to look deeper until next week.

Thanks for keeping up on it.

**Comment by jeaye** [comment] 2016-09-11 18:32
I'm looking further into this now.

**Comment by jeaye** [comment] 2016-09-11 20:52
I've pinned down the root of the issue. When creating an uberwar (not uberjar) for GAE, tufte acts as though compile-time elision is enabled (given its output), but running the code in the exploded war results in thread creation as though there was no elision. I've reproduced this in a trivial test repository here: https://github.com/jeaye/tufte-test

That repo uses a custom `my/tufte`, which is just a local repo using `lein-localrepo` with the following change:

```diff
diff --git a/src/taoensso/tufte/impl.cljx b/src/taoensso/tufte/impl.cljx
index e6c7f08..a7c47d0 100644
--- a/src/taoensso/tufte/impl.cljx
+++ b/src/taoensso/tufte/impl.cljx
@@ -193,6 +193,7 @@
                   ;; Note: just drop if no registered handlers
                   (handle-blocking! m)
                   (recur))))]
+      (println "TUFTE Starting thread")
       (doto (Thread. f)
         (.setDaemon true)
         (.start)))))
```

The following session demonstrates my point:
```shell
┌─(✓)[jeaye@max]─[~/projects/tufte-test][12:25:11][master]
└──╼ export TUFTE_MIN_LEVEL=6
┌─(✓)[jeaye@max]─[~/projects/tufte-test][12:25:21][master]
└──╼ lein ring uberwar
Compiling tufte-test.core
Compile-time (elision) Tufte min-level: 6
Compile-time (elision) Tufte min-level: 6
Created /Users/jeaye/projects/tufte-test/target/uberjar/tufte-test-0.1.0-SNAPSHOT-standalone.war
┌─(✓)[jeaye@max]─[~/projects/tufte-test][12:25:43][master]
└──╼ unset TUFTE_MIN_LEVEL
┌─(✓)[jeaye@max]─[~/projects/tufte-test][12:25:50][master]
└──╼ rm -rf war; mkdir war; cd war; jar xf ../target/uberjar/tufte-test-0.1.0-SNAPSHOT-standalone.war; cd WEB-INF
┌─(✓)[jeaye@max]─[~/projects/tufte-test/war/WEB-INF][12:25:57][master]
└──╼ java -classpath "lib/*:classes/." tufte_test.core
meow
TUFTE Starting thread
```

Hopefully this is conclusive enough for you to be able to reproduce. A full session, including cloning the repo, is shown here: https://gist.github.com/jeaye/707b2c3db0a4228e33c271d42a3071dd

Thanks for your time.

**Comment by ptaoussanis** [comment] 2016-09-12 03:47
> I've pinned down the root of the issue. When creating an uberwar (not uberjar) for GAE, tufte acts as though compile-time elision is enabled (given its output), but running the code in the exploded war results in thread creation as though there was no elision.

Thanks for the reproducible. Have you confirmed that the uberwar's environment is correctly configured? Perhaps try modify your handler fn to return the value of
`(str "min-level: " (taoensso.encore/read-sys-val "TUFTE_MIN_LEVEL"))`?

**Comment by jeaye** [comment] 2016-09-12 03:51
The environment of the GAE machine running the program doesn't have `TUFTE_MIN_LEVEL` set, as I was expecting that, as it's a compile-time value, it's only needed at compile-time. In my tests today, I've found that setting `TUFTE_MIN_LEVEL`, when running from the exploded WAR, results in the expected behavior.

Do you know why AOT isn't working as expected with the WAR and is it something that either tufte or I can change?

**Comment by ptaoussanis** [comment] 2016-09-12 04:04
> The environment of the GAE machine running the program doesn't have TUFTE_MIN_LEVEL

That could be the problem, is there a reason you're trying to avoid setting the environment variable on the GAE machine?

> Do you know why AOT isn't working as expected with the WAR and is it something that either tufte or I can change?

Clojure's AOT can unfortunately often be confusing, especially once you start working with things like compiled WARs that introduce their own layers of complexity.

"Compile time" isn't always as straight forward as you might expect coming from other non-dynamic languages. For example, there can often be nuanced distinctions between macro-expansion time (what actually matters here), and when you produce a WAR.

Would recommend that you start by setting the correct environment variables for your WAR environment and establishing whether that produces the expected output or not. Let's go from there.

**Comment by jeaye** [comment] 2016-09-12 04:34
> Clojure's AOT can unfortunately often be confusing, especially once you start working with things like compiled WARs that introduce their own layers of complexity.
> 
> "Compile time" isn't always as straight forward as you might expect coming from other non-dynamic languages. For example, there can often be nuanced distinctions between macro-expansion time (what actually matters here), and when you produce a WAR.

That's good information, thank you; it also aligns with what I've been seeing during my testing.

> Would recommend that you start by setting the correct environment variables for your WAR environment and establishing whether that produces the expected output or not. Let's go from there.

Right. I have found that setting the environment variables in the WAR environment results in the expected elision. My confusion was around "AOT" with regard to WARs.

Thanks again for working with me on this; what do you think about mentioning this in the README? Something like: "It's recommended to specify TUFTE_MIN_LEVEL in the run-time environment as well as the compile-time environment, as some compiled archives don't perform thorough AOT."

**Comment by ptaoussanis** [comment] 2016-09-12 04:43
>Thanks again for working with me on this; what do you think about mentioning this in the README? 

No problem, happy you have a solution.

Reasonable suggestion re: the README, will consider that - thanks. Would just want a little time to settle on the right level of exposition. Ideally could link somewhere else that describes the situation in detail. Will come back to this when I have a little time.

**Comment by ptaoussanis** [comment] 2016-10-10 04:45
Closing for now, have made a note in my TODOs to take a look at the docs on this when I'm doing a batch of work on Tufte again.

**Closed** 2016-10-10 04:44 UTC
